<?php

add_option('vkrwps_mem', 'admin@myshop.com');
add_option('vkrwps_shopname', 'My Shop');
add_option('vkrwps_cart_display', 'simple');
add_option('vkrwps_checkout_page', 'checkout');
add_option('vkrwps_checkout_text', 'Checkout');
add_option('vkrwps_empty_cart_s', 'Your cart is empty');
add_option('vkrwps_sppk', 0);
add_option('vkrwps_cart_div', '');
add_option('vkrwps_co_div', '');
add_option('vkrwps_currency', '$');
add_option('vkrwps_cart_total_s', 'Subtotal:');
add_option('vkrwps_cart_total_wt_s', 'Total with tax:');
add_option('vkrwps_sci_s', 'items = $');
add_option('vkrwps_clear_cart_s', 'Clear cart' );
add_option('vkrwps_addtocart_s', 'Add to cart' );
add_option('vkrwps_pdetails_s', 'Product Details');
add_option('vkrwps_add_again_p_text', '+');
add_option('vkrwps_remove_one_p_text', '-');
add_option('vkrwps_clear_p_s', 'delete');
add_option('vkrwps_step2_s', 'Step 2');
add_option('vkrwps_backts1_s', 'Back to Step 1');
add_option('vkrwps_step3_s', 'Step 3');
add_option('vkrwps_backts2_s', 'Back to Step 2');
add_option('vkrwps_finish_co_s', 'Finish checkout');
add_option('vkrwps_tax', 0);
add_option('vkrwps_taxtext', 'Tax:');
add_option( 'vkrwps_pricetext', 'Price:' );
add_option( 'vkrwps_weighttext', 'Weight:' );
add_option( 'vkrwps_weightmtext', 'kg' );
add_option( 'vkrwps_sps', 'Shipping price:' );
add_option( 'vkrwps_twtas','Grand total:' );
add_option( 'vkrwps_pcss', 'yes' );
add_option( 'vkrwps_symba', 'before' );
add_option( 'vkrwps_pat', 'The product has been added' );
add_option( 'vkrwps_prt', 'The product has been removed' );
add_option( 'vkrwps_oid', 1111 );
add_option( 'vkrwps_paging', 9 );
add_option( 'vkrwps_orders_paging', 10 );
add_option( 'vkrwps_ppotext', "Thank you for your order. \r\n \r\n You will now be taken to the paypal website to complete your order." );
add_option( 'vkrwps_ootext', 'Thank you for your order.' );
add_option( 'vkrwps_ooss', 'This product is out of stock.' );
add_option( 'vkrwps_dateformat', 'normaldate' );
add_option( 'vkrwps_orderconftext', "Thank you for your order! \r\n \r\n You can review your order information below:" );
add_option( 'vkrwps_ae_subj', 'New order! Order No.' );
add_option( 'vkrwps_cps', 'Order Status Update - Order No.' );
add_option( 'vkrwps_ce_subj', 'Your order has been received. Order No.' );
add_option( 'vkrwps_aoef', 'yes' );
add_option( 'vkrwps_pdo', 'asc' );
add_option( 'vkrwps_s1tt', '' );
add_option( 'vkrwps_s2tt', '' );
add_option( 'vkrwps_s3tt', '' );
add_option( 'vkrwps_ppemail', 'real' );
add_option('vkrwps_nltc', '#000');
add_option('vkrwps_nlbc', '#5d2e8b');
add_option('vkrwps_nltextc', '#777');
add_option('vkrwps_mon', '100');

?>